###############################################################################
#                           Common                              #
###############################################################################
[common]
   version = "0.1.0" 
   is_debug = true
   log_level = "debug"
   log_path = "./out.log"

###############################################################################
#                                   AGENT                                     #
###############################################################################
[agent]
    interval = 15
    flush_interval = 10
    metric_batch_size = 10000

[global_filters]
    collectorsdrop = ["kernel"]
    reportersdrop = []


###############################################################################
#                                   COLLECTORS                                #
###############################################################################

[[collectors.cpu]]
    percpu = false
    totalcpu = true
    interval = 5

[[collectors.disk]]
    mount_points = ["/"]
    ignore_fs = ["tmpfs", "devtmpfs"]
    reporters = ["udp", "influxdb"]

[[collectors.mycollector]]
    addr = "loaclhost:9999"
	descr = ["111", "2222", "3333"]



###############################################################################
#                                   REPORTERS                                 #
###############################################################################

[[reporters.influxdb]]


###############################################################################
#                                   DATAS                                      #
###############################################################################

[datas.metric]
    collectors = ["cpu"]
    reporters = ["udp", "influxdb"]
    chan_size = 100
    name = "metric"


[datas.log]
    collectors = []
    reporters = []



