###############################################################################
#                           Common                              #
###############################################################################
[common]
   version = "0.1.0" 
   is_debug = true
   log_level = "debug"
   log_path = "./out.log"

###############################################################################
#                                   AGENT                                     #
###############################################################################
[agent]
    name = "apollo"
    use_env = true
    env = "APOLLO_TEST"
    size = 1000
    # interval = 15
    # flush_interval = 10
    # metric_batch_size = 10000

[etcd]
    addrs = ["10.7.24.191:2379","10.7.24.192:2379"]
    dltimeout = 10
    rqtimeout = 10
    watch_dir = "/openapm/collector/reportdir2"
    ttl = 10

[global_filters]
    collectorsdrop = ["kernel"]
    reportersdrop = []


###############################################################################
#                                   COLLECTORS                                #
###############################################################################

[[collectors.cpu]]
    percpu = false
    totalcpu = true
    interval = 5
    trans_name = "metric"

[[collectors.disk]]
    mount_points = ["/"]
    ignore_fs = ["tmpfs", "devtmpfs"]
    reporters = ["udp", "influxdb"]
    data = "metric"


###############################################################################
#                                   REPORTERS                                 #
###############################################################################

[[reporters.influxdb]]
    # urls = ["http://10.7.25.42:8086"]
    urls = ["http://10.100.7.46:8086"]
    #正式环境
    #  urls: http://10.33.36.123:8086
    data_base = "metrics"
    write_consistency = "any"
    timeout = 5
    time_task = 1000
    data_len = 100


###############################################################################
#                                   DATAS                                     #
###############################################################################

[[datas.metric]]
    collectors = ["cpu"]
    reporters = ["influxdb"]
    chan_size = 100


[[datas.log]]
    collectors = ["cpu"]
    reporters = ["influxdb"]
    chan_size = 100



